### ISSUE TITLE
Building image failed with copr bootc-202501150117.gdc7d4cf320-1.el10.x86_64 and rpm-ostree-2024.8.125.g1dc4295e-1.el10.x86_64

### ISSUE THREAD

**Issue by henrywang** [containers/bootc#1033]
Build bootc image with copr bootc and rpm-ostree updated based on `centos-bootc:steram10` image. Build failed today.

`bootc-202501131649.g8dff32080b-1.el10.x86_64` + `rpm-ostree-2024.8.125.g1dc4295e-1.el10.x86_64` did not have this building error yesterday.

But today, `bootc-202501150117.gdc7d4cf320-1.el10.x86_64` with the same version of rpm-ostree failed to build image

```
Error: Transaction test error:
file /usr/libexec/libostree/ext/ostree-container conflicts between attempted installs of rpm-ostree-2024.8.125.g1dc4295e-1.el10.x86_64 and bootc-202501150117.gdc7d4cf320-1.el10.x86_64
file /usr/libexec/libostree/ext/ostree-ima-sign conflicts between attempted installs of rpm-ostree-2024.8.125.g1dc4295e-1.el10.x86_64 and bootc-202501150117.gdc7d4cf320-1.el10.x86_64
file /usr/libexec/libostree/ext/ostree-provisional-repair conflicts between attempted installs of rpm-ostree-2024.8.125.g1dc4295e-1.el10.x86_64 and bootc-202501150117.gdc7d4cf320-1.el10.x86_64
```

**Comment by cgwalters** [comment]
I think this should be fixed since https://github.com/coreos/rpm-ostree/pull/5229 right?
Looking at https://copr.fedorainfracloud.org/coprs/g/CoreOS/continuous/build/8526948/ there are just two failures, one in fedora eln and one in fedora-40-s390x.

I'm going to drop fedora-40 from that copr, we can not care about it anymore.

**Comment by henrywang** [comment]
For CS10 and Fedora, still have this issue:
`file /usr/libexec/libostree/ext/ostree-container conflicts between attempted installs of rpm-ostree-2025.1.10.g84a07211-1.el10.x86_64 and bootc-202501172158.ge8bb9f748f-1.el10.x86_64`

**Comment by cgwalters** [comment]
https://github.com/coreos/rpm-ostree/pull/5237

**Comment by cgwalters** [comment]
I had to do another fix but https://gitlab.com/fedora/bootc/base-images-dev/-/pipelines/1634896909 is building again

**Comment by henrywang** [comment]
Issue verified.
